// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Chat(arg1:string):Promise<string>;

export function ChatAudio(arg1:string):Promise<main.AudioResponse>;

export function GetScreenSize():Promise<main.ScreenSize>;

export function GetWindowPosition():Promise<main.WindowPos>;

export function Greet(arg1:string):Promise<string>;

export function Interact():Promise<string>;

export function MoveWindow(arg1:number,arg2:number):Promise<void>;

export function SelectImage():Promise<string>;

export function SetCompanionName(arg1:string):Promise<void>;

export function Speak(arg1:string):Promise<string>;
