// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Chat(arg1) {
  return window['go']['main']['App']['Chat'](arg1);
}

export function ChatAudio(arg1) {
  return window['go']['main']['App']['ChatAudio'](arg1);
}

export function GetScreenSize() {
  return window['go']['main']['App']['GetScreenSize']();
}

export function GetWindowPosition() {
  return window['go']['main']['App']['GetWindowPosition']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Interact() {
  return window['go']['main']['App']['Interact']();
}

export function MoveWindow(arg1, arg2) {
  return window['go']['main']['App']['MoveWindow'](arg1, arg2);
}

export function SelectImage() {
  return window['go']['main']['App']['SelectImage']();
}

export function SetCompanionName(arg1) {
  return window['go']['main']['App']['SetCompanionName'](arg1);
}

export function Speak(arg1) {
  return window['go']['main']['App']['Speak'](arg1);
}
